--[[ ----------------------------------------------------------------------------------------------
 File       : keylogger.script
 Description: Кейлоггер
 Author     : Charsi
 Last edit  : 24.03.2024
--]] ----------------------------------------------------------------------------------------------
----------------------------------------
-- Общие переменные модуля
----------------------------------------
local sModule = script_name() -- / строковое имя файла-модуля
local con = get_console()
local screen_w, screen_h = nil, nil

-- параметры автоматического (при загрузке) назначения клавиш
-- key    - назначаемая клавиша
-- action - функция / текстовая ссылка на функцию
local tbinding = {
}

----------------------------------------
-- Инициализация
----------------------------------------

function init()
	DIK_keys.MOUSE_4 = 340
	DIK_keys.MOUSE_5 = 341
	-- xr_s.register_callback("game_load", on_load)
end

function on_load()
	for _, v in ipairs(tbinding) do bind_console_key(v.key, v.action) end
	xr_s.register_callback("update", update)
end

function update()
	local sw, sh = con:get_string("vid_mode"):match("(%d+)x(%d+)")
	if sh ~= screen_h or sw ~= screen_w then
		if sh == "0" then -- "key_codex0"
			con:execute("vid_mode " .. screen_w .. "x" .. screen_h)
			xr_s.on_event("on_btn_" .. sw, {key = sw})
		else
			screen_w, screen_h = sw, sh
		end
	end
end

function bind_console_key(key, action)
	if type(key) ~= 'string' then return end
	local f = Get_CheckedFunc(action)
	if f then
		local key_code = DIK_keys["DIK_" .. string.upper(key)]
		if key_code then
			con:execute("bind_console vid_mode " .. key_code .. "x0 k" .. key)
			xr_s.register_callback("on_btn_" .. key_code, f)
			xr_s.register_callback("actor_destroy", function() unbind_console_key(key) end)
		else
			key_code = DIK_keys[string.upper(key)]
			if key_code then -- mouse btns
				con:execute("bind_console vid_mode " .. key_code .. "x0 " .. key:gsub("_", ""))
				xr_s.register_callback("on_btn_" .. key_code, f)
				xr_s.register_callback("actor_destroy", function() unbind_console_key(key) end)
			end
		end
	else
		-- printf("bind_console_dbg:no_action_for_key_"..key)
	end
end

function unbind_console_key(key)
	if DIK_keys["DIK_" .. string.upper(key)] then
		con:execute("unbind_console k" .. key)
	elseif DIK_keys[string.upper(key)] and key:lower():match "^mouse_%d$" then -- mouse btns
		con:execute("unbind_console " .. key:gsub("_", ""))
	end
end

local keys = {
	[1] = 'ESCAPE',
	[2] = '1',
	[3] = '2',
	[4] = '3',
	[5] = '4',
	[6] = '5',
	[7] = '6',
	[8] = '7',
	[9] = '8',
	[10] = '9',
	[11] = '0',
	[12] = 'MINUS',
	[13] = 'EQUALS',
	[14] = 'BACK',
	[15] = 'TAB',
	[16] = 'Q',
	[17] = 'W',
	[18] = 'E',
	[19] = 'R',
	[20] = 'T',
	[21] = 'Y',
	[22] = 'U',
	[23] = 'I',
	[24] = 'O',
	[25] = 'P',
	[26] = 'LBRACKET',
	[27] = 'RBRACKET',
	[28] = 'RETURN',
	[29] = 'LCONTROL',
	[30] = 'A',
	[31] = 'S',
	[32] = 'D',
	[33] = 'F',
	[34] = 'G',
	[35] = 'H',
	[36] = 'J',
	[37] = 'K',
	[38] = 'L',
	[39] = 'SEMICOLON',
	[40] = 'APOSTROPHE',
	[41] = 'GRAVE',
	[42] = 'LSHIFT',
	[43] = 'BACKSLASH',
	[44] = 'Z',
	[45] = 'X',
	[46] = 'C',
	[47] = 'V',
	[48] = 'B',
	[49] = 'N',
	[50] = 'M',
	[51] = 'COMMA',
	[52] = 'PERIOD',
	[53] = 'SLASH',
	[54] = 'RSHIFT',
	[55] = 'MULTIPLY',
	[56] = 'LMENU',
	[57] = 'SPACE',
	[58] = 'CAPITAL',
	[59] = 'F1',
	[60] = 'F2',
	[61] = 'F3',
	[62] = 'F4',
	[63] = 'F5',
	[64] = 'F6',
	[65] = 'F7',
	[66] = 'F8',
	[67] = 'F9',
	[68] = 'F10',
	[69] = 'NUMLOCK',
	[70] = 'SCROLL',
	[71] = 'NUMPAD7',
	[72] = 'NUMPAD8',
	[73] = 'NUMPAD9',
	[74] = 'SUBTRACT',
	[75] = 'NUMPAD4',
	[76] = 'NUMPAD5',
	[77] = 'NUMPAD6',
	[78] = 'ADD',
	[79] = 'NUMPAD1',
	[80] = 'NUMPAD2',
	[81] = 'NUMPAD3',
	[82] = 'NUMPAD0',
	[83] = 'DECIMAL',
	[87] = 'F11',
	[88] = 'F12',
	[100] = 'F13',
	[101] = 'F14',
	[102] = 'F15',
	[112] = 'KANA',
	[121] = 'CONVERT',
	[123] = 'NOCONVERT',
	[125] = 'YEN',
	[141] = 'NUMPADEQUALS',
	[144] = 'CIRCUMFLEX',
	[145] = 'AT',
	[146] = 'COLON',
	[147] = 'UNDERLINE',
	[148] = 'KANJI',
	[149] = 'STOP',
	[150] = 'AX',
	[151] = 'UNLABELED',
	[156] = 'NUMPADENTER',
	[157] = 'RCONTROL',
	[179] = 'NUMPADCOMMA',
	[181] = 'DIVIDE',
	[183] = 'SYSRQ',
	[184] = 'RMENU',
	[197] = 'PAUSE',
	[199] = 'HOME',
	[200] = 'UP',
	[201] = 'PRIOR',
	[203] = 'LEFT',
	[205] = 'RIGHT',
	[207] = 'END',
	[208] = 'DOWN',
	[209] = 'NEXT',
	[210] = 'INSERT',
	[211] = 'DELETE',
	[219] = 'LWIN',
	[220] = 'RWIN',
	[221] = 'APPS'
}

-- аргумент - код действия из перечисления key_bindings
-- для спринта bind_to_keyname( key_bindings.kACCEL ) вернет строку 'X', если спринт назначен на X
function bind_to_keyname(iNum)
	for k, v in pairs(keys) do if DIK_keys["DIK_" .. v] and dik_to_bind(DIK_keys["DIK_" .. v]) == iNum then return v end end
	return ""
end
