local registred_items = {}
-- Outfits ---------------------------------------------------------------------
class "se_outfit" (cse_alife_item_custom_outfit)
function se_outfit:__init (section) super (section)
	self.secret_item = false
end
function se_outfit:on_register()
	cse_alife_item_custom_outfit.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)

	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_outfit:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_custom_outfit.on_unregister( self )
end
function se_outfit:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_custom_outfit.can_switch_online(self)
end

class "se_helmet" (cse_alife_item_helmet)
function se_helmet:__init (section) super (section)
	self.secret_item = false
end
function se_helmet:on_register()
	cse_alife_item_helmet.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)

	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_helmet:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_helmet.on_unregister( self )
end
function se_helmet:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_helmet.can_switch_online(self)
end

-- Weapons ---------------------------------------------------------------------
class "se_weapon" (cse_alife_item_weapon)
function se_weapon:__init (section) super (section)
	self.secret_item = false
end
function se_weapon:on_register()
	cse_alife_item_weapon.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)


	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_weapon:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_weapon.on_unregister( self )
end
function se_weapon:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_weapon.can_switch_online(self)
end

class "se_weapon_shotgun" (cse_alife_item_weapon_shotgun)
function se_weapon_shotgun:__init (section) super (section)
	self.secret_item = false
end
function se_weapon_shotgun:on_register()
	cse_alife_item_weapon_shotgun.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_weapon_shotgun:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_weapon_shotgun.on_unregister( self )
end
function se_weapon_shotgun:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_weapon_shotgun.can_switch_online(self)
end

class "se_weapon_automatic_shotgun" (cse_alife_item_weapon_auto_shotgun)
function se_weapon_automatic_shotgun:__init (section) super (section)
	self.secret_item = false
end
function se_weapon_automatic_shotgun:on_register()
	cse_alife_item_weapon_auto_shotgun.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_weapon_automatic_shotgun:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_weapon_auto_shotgun.on_unregister( self )
end
function se_weapon_automatic_shotgun:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_weapon_auto_shotgun.can_switch_online(self)
end

class "se_weapon_magazined" (cse_alife_item_weapon_magazined)
function se_weapon_magazined:__init (section) super (section)
	self.secret_item = false
end
function se_weapon_magazined:on_register()
	cse_alife_item_weapon_magazined.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_weapon_magazined:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_weapon_magazined.on_unregister( self )
end
function se_weapon_magazined:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_weapon_magazined.can_switch_online(self)
end

class "se_weapon_magazined_w_gl" (cse_alife_item_weapon_magazined_w_gl)
function se_weapon_magazined_w_gl:__init (section) super (section)
	self.secret_item = false
end
function se_weapon_magazined_w_gl:on_register()
	cse_alife_item_weapon_magazined_w_gl.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_weapon_magazined_w_gl:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_weapon_magazined_w_gl.on_unregister( self )
end
function se_weapon_magazined_w_gl:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_weapon_magazined_w_gl.can_switch_online(self)
end

-- Items -----------------------------------------------------------------------
class "se_item"	(cse_alife_item)
function se_item:__init (section) super (section)
	self.secret_item = false
end
function se_item:on_register()
	cse_alife_item.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_item:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item.on_unregister( self )
end
function se_item:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item.can_switch_online(self)
end

class "se_item_torch" (cse_alife_item_torch)
function se_item_torch:__init (section) super (section)
	self.secret_item = false
end
function se_item_torch:on_register()
	cse_alife_item_torch.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_item_torch:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_torch.on_unregister( self )
end
function se_item_torch:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_torch.can_switch_online(self)
end

--' ФИзобъекты
class "se_physic" (cse_alife_object_physic)
function se_physic:__init (section) super (section)
	self.secret_item = false
	self.code_set    = false
	
	self.door 		 = section and section == "physic_door"	
	self.door_lab_x8 = section and section == "door_lab_x8"
	
	self.has_playing_sound = false
	self.playing_time_start = 0
	self.local_id = 0
	self.played_id = 0
	
	if self.door then
		self.door_opened = false
	end
	
	if self.door_lab_x8 then
		self.anim_time = 0
	end
end
function se_physic:on_register()
	cse_alife_object_physic.on_register(self)
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_physic:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_object_physic.on_unregister(self)
end
function se_physic:keep_saved_data_anyway()
	return true
end
function se_physic:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_object_physic.can_switch_online(self)
end
function se_physic:STATE_Read(packet, size)
	cse_alife_object_physic.STATE_Read(self, packet, size)
	-- под LevelEditor не пытаться читать из пакета ничего
	if editor() then
		return
	end
	
	if self.script_version > 12 then
		self.has_playing_sound = packet:r_bool()
		if self.has_playing_sound then
			self.local_id = packet:r_u16() 
			self.played_id = packet:r_u8()
			self.playing_time_start = packet:r_u32()
		end
		
		self.code_set = packet:r_bool()
		
		if self.door then
			self.door_opened = packet:r_bool()
		elseif self.door_lab_x8 then
			self.anim_time = packet:r_float()
		end
	end
end

function se_physic:STATE_Write(packet)
	cse_alife_object_physic.STATE_Write(self, packet)
	-- под LevelEditor не пытаться читать из пакета ничего
	if editor() then
		return
	end
	
	packet:w_bool(self.has_playing_sound)
	if self.has_playing_sound then
		packet:w_u16(self.local_id) 
		packet:w_u8(self.played_id)
		packet:w_u32(self.playing_time_start)
	end
	
	packet:w_bool(self.code_set)
	
	if self.door then
		packet:w_bool(self.door_opened)
	elseif self.door_lab_x8 then
		packet:w_float(self.anim_time)
	end
end

class "se_lamp" (cse_alife_object_hanging_lamp)
function se_lamp:__init (section) super (section)
	self.secret_item = false
end
function se_lamp:on_register()
	cse_alife_object_hanging_lamp.on_register(self)
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
	-- +UDP
	self.pk = get_netpk(self, 1)
	self.data = {}
	local flags = {}
	if self.pk:isOk() then
		self.data = self.pk:get()
		flags = utils.parse_lamp_flags(self.data.light_flags)
	end

	local section = self:section_name()
	local ini = system_ini()

	self.range 				= utils.cfg_get_number(ini, section, "range", 			self, false, self.data.main_range or 5)
	self.brightness			= utils.cfg_get_number(ini, section, "brightness", 		self, false, self.data.main_brightness or 1)
	self.color				= utils.cfg_get_color(ini, section,  "color", 			self, false, self.data.main_color or GetARGB(1.0,1.0,1.0,1.0))
	self.color_animator		= utils.cfg_get_string(ini, section, "color_animator", 	self, false, "", self.data.main_color_animator or "")
	self.cone_angle 		= utils.cfg_get_number(ini, section, "cone_angle", 		self, false, self.data.main_cone_angle or 90)

	self.physic 			= utils.cfg_get_bool(ini, section, "physic", 		self, false, flags.physic or false)
	self.cast_shadow 		= utils.cfg_get_bool(ini, section, "cast_shadow", 	self, false, flags.cast_shadow or true)
	self.type_spot 			= utils.cfg_get_bool(ini, section, "type_spot", 	self, false, flags.type_spot or false)
	self.point_ambient 		= utils.cfg_get_bool(ini, section, "point_ambient", self, false, flags.point_ambient or false)
	self.r1 = true
	self.r2 = true

	self.visual_name 		= utils.cfg_get_string(ini, section, "visual_name", 		self, false, "", self.data.visual_name or "")
	self.bone 				= utils.cfg_get_string(ini, section, "bone",				self, false, "", self.data.main_bone or "")
	self.fixed_bones		= utils.cfg_get_string(ini, section, "fixed_bones", 		self, false, "", self.data.lamp_fixed_bones or "")
	self.startup_animation	= utils.cfg_get_string(ini, section, "startup_animation", 	self, false, "", self.data.startup_animation or "")

	self.glow_texture 		= utils.cfg_get_string(ini, section, "glow_texture",self, false, "",self.data.glow_texture or "")
	self.glow_radius 		= utils.cfg_get_number(ini, section, "glow_radius", self, false, 	self.data.glow_radius or 0.25)

	self.ambient_radius 	= utils.cfg_get_number(ini, section, "ambient_radius", 	self, false, self.data.ambient_radius or 1)
	self.ambient_power 		= utils.cfg_get_number(ini, section, "ambient_power", 	self, false, self.data.ambient_power or 0.5)
	self.ambient_texture 	= utils.cfg_get_string(ini, section, "ambient_texture", self, false, "", self.data.ambient_texture or "")
	self.ambient_bone 		= utils.cfg_get_string(ini, section, "ambient_bone", 	self, false, "", self.data.ambient_bone or "")
	-- -UDP
end
function se_lamp:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_object_hanging_lamp.on_unregister(self)
end
function se_lamp:keep_saved_data_anyway()
	return true
end
-- +UDP
function se_lamp:switch_online()
	--to_log(string.exformat("se_lamp:switch_online %s", self:name()))
	if self.pk:isOk() then
		self.data.main_color = self.color
		self.data.main_color_animator = self.color_animator
		self.data.main_range = self.range
		self.data.main_brightness = self.brightness
		self.data.main_cone_angle = self.cone_angle

		self.data.ambient_power = self.ambient_power
		self.data.ambient_radius = self.ambient_radius
		self.data.ambient_texture = self.ambient_texture
		self.data.ambient_bone = self.ambient_bone

		self.data.light_flags = utils.build_lamp_flags(self)
		
		self.data.visual_name = self.visual_name
		self.data.main_bone = self.bone
		self.data.lamp_fixed_bones = self.fixed_bones
		self.data.startup_animation = self.startup_animation
		
		self.data.glow_texture = self.glow_texture
		self.data.glow_radius = self.glow_radius
		
		--table.print(self.data)
		self.pk:set(self.data)
	end
	cse_alife_object_hanging_lamp.switch_online(self)
end

function se_lamp:set_online_pos(pos, threshold)
	if not threshold then
		threshold = 0.25
	end

	self.position = pos
	-- to_log(string.exformat("target_pos:distance_to_sqr %s", target_pos:distance_to_sqr(sobj.position)))
	local obj = level.object_by_id(self.id)
	if obj then
		if obj:position():distance_to_sqr(self.position) > threshold * threshold then
			-- need update visibility
			--to_log(string.exformat("Position %s %s", obj:position(), self.position))
			--self.object:set_const_force(self.dir, force, 2)
			--to_log("switch_offline %s", self:name())
			self:switch_offline()
			--to_log("switch_online %s", self:name())
			self:switch_online()
		end
	elseif self.online == false then
		--to_log("switch_online 2 %s", self:name())
		self:switch_online()
	elseif self.online == true then
		--to_log("switch_offline 2 %s", self:name())
		self:switch_offline()
	end
end
-- -UDP
function se_lamp:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_object_hanging_lamp.can_switch_online(self)
end
function se_lamp:STATE_Write(packet)
	cse_alife_object_hanging_lamp.STATE_Write(self, packet)
	-- под LevelEditor не пытаться читать из пакета ничего
	if editor() then
		return
	end
	
	
end
function se_lamp:STATE_Read(packet, size)
	cse_alife_object_hanging_lamp.STATE_Read(self, packet, size)
	-- под LevelEditor не пытаться читать из пакета ничего
	if editor() then
		return
	end

end

-- AMMO ------------------------------------------------------------------------
class "se_ammo" (cse_alife_item_ammo)
function se_ammo:__init (section) super (section)
	self.secret_item = false
end

function se_ammo:on_register()
	cse_alife_item_ammo.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end

function se_ammo:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_item_ammo.on_unregister(self)
end
function se_ammo:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_ammo.can_switch_online(self)
end
-- GRENADES --------------------------------------------------------------------------------------------------------------------------
class "se_grenade" (cse_alife_item_grenade)
function se_grenade:__init (section) super (section)
	self.secret_item = false
end

function se_grenade:on_register()
	cse_alife_item_grenade.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end

function se_grenade:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_item_grenade.on_unregister(self)
end
function se_grenade:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_grenade.can_switch_online(self)
end
-- EATEBLE ---------------------------------------------------------------------------------------------------------------------------
class "se_eatable" (cse_alife_item)
function se_eatable:__init (section) super (section)
	self.secret_item = false
end

function se_eatable:on_register()
	cse_alife_item.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end

function se_eatable:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_item.on_unregister(self)
end
function se_eatable:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item.can_switch_online(self)
end

-- INVENTORY BOX ---------------------------------------------------------------------------------------------------------------------
class "se_invbox" (cse_alife_inventory_box)
function se_invbox:__init (section) super (section)
	self.secret_item = false
end

function se_invbox:on_register()
	cse_alife_inventory_box.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end

function se_invbox:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_inventory_box.on_unregister(self)
end
function se_invbox:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_inventory_box.can_switch_online(self)
end

-- EXPLOSIVE -------------------------------------------------------------------------------------------------------------------------
class "se_explosive" (cse_alife_item_explosive)
function se_explosive:__init (section) super (section)
	self.secret_item = false
end

function se_explosive:on_register()
	cse_alife_item_explosive.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end

function se_explosive:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_item_explosive.on_unregister(self)
end
function se_explosive:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_explosive.can_switch_online(self)
end

-- PDA -------------------------------------------------------------------------------------------------------------------------------
class "se_pda" (cse_alife_item_pda)
function se_pda:__init (section) super (section)
	self.secret_item = false
end

function se_pda:on_register()
	cse_alife_item_pda.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end

function se_pda:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_item_pda.on_unregister(self)
end
function se_pda:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_pda.can_switch_online(self)
end

class "se_detector" (cse_alife_item_detector)
function se_detector:__init (section) super (section)
	self.secret_item = false
end
function se_detector:on_register()
	cse_alife_item_detector.on_register( self )
	-- Проверяем кастомдату обьекта на наличие стори айди.
	story_objects.check_spawn_ini_for_story_id(self)
	-- Собираем статистику по предметам.
	if registred_items[self:section_name()] == nil then
		registred_items[self:section_name()] = 1
	else
		registred_items[self:section_name()] = registred_items[self:section_name()] + 1
	end

	self.secret_item = treasure_manager.get_treasure_manager():register_item(self)
end
function se_detector:on_unregister()
	--' Отрегистрация в таскменеджере
	unregister_story_object_by_id(self.id)
	cse_alife_item_detector.on_unregister( self )
end
function se_detector:can_switch_online()
	if(self.secret_item) then
		return false
	end
	return cse_alife_item_detector.can_switch_online(self)
end

class "se_projector"	(cse_alife_object_projector)
--------------------
function se_projector:__init (section) super (section)
end

function se_projector:on_register()
	cse_alife_object_projector.on_register(self)
	story_objects.check_spawn_ini_for_story_id(self)
end

function se_projector:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_object_projector.on_unregister(self)
end

class "se_guitar"	(cse_alife_item_guitar)
--------------------
function se_guitar:__init (section) super (section)
end

function se_guitar:on_register()
	cse_alife_item_guitar.on_register(self)
	story_objects.check_spawn_ini_for_story_id(self)
end

function se_guitar:on_unregister()
	unregister_story_object_by_id(self.id)
	cse_alife_item_guitar.on_unregister(self)
end

--------------------------------------------------------------------------------
function stats()
	printf("*** SIM ITEMS STATISTIC ***")
	for k,v in pairs(registred_items) do
		printf("item = %s, num = %s", k, v)
	end
end
