----------------------------------------------------------------------------------------------------
-- Use restrictor as button
----------------------------------------------------------------------------------------------------

function change_button_state_on_client(id)

	if db.storage[id].sr_button ~= nil then
		local button = db.storage[id].sr_button.button_action
		
		if button ~= nil then
			button:try_switch()
		end
	end
	
end

class "sr_button"

function sr_button:__init(obj, storage)
	self.object = obj
	self.st = storage
	
	self.hold_percent = 0.0
	storage.button_action = self
end

function sr_button:reset_scheme()
	self.object:set_shape_flag(true)
	
	if self.st.hold then
		self:reset_hold()
		self.object:set_callback(callback.hold_object, self.hold_callback, self)
	end
end

function sr_button:deactivate()
	self.object:set_shape_flag(false)
end

function sr_button:reset_hold()
	self.object:set_using_object(false)
    self.hold_percent = 0.0
	
	if getLocalActor() ~= nil then
		getLocalActor():set_action_percent(self.hold_percent)
	end
end

function sr_button:complete_hold()
	self:reset_hold()
	self.object:set_callback(callback.hold_object, nil)	
end

function sr_button:use_callback(victim, who)
	--Server already knows that client pushed at the object, so switch state on the server
	--if switch is success, send packet to the client
	--Сервер уже знает, что клиент нажал на объект, поэтому переключаем стейт на сервере 
	--и в случае успеха, отправляем пакет клиенту
	if (OnServer() and not self.st.local_use) or 
		(OnClient() and self.st.local_use) then
		if self:try_switch() then
			return
		end
	end
end

function sr_button:hold_callback(obj, who, delta)
	if not self.st.hold then
		return
	end
	
	if xr_logic.try_switch_to_another_section(self.object, self.st, db.actor) then
		self:reset_hold()
		return
	end
	
	self.hold_percent = self.hold_percent + 0.01 * (delta * self.st.hold_multi)
	self.last_hit_tm = time_global()
	self.object:set_using_object(true) --поставим флаг в движке, что мы юзаем скриптовый предмет
	
	if getLocalActor() ~= nil then
		getLocalActor():set_action_percent(self.hold_percent)
	end
	
	if self.hold_percent > 99 then
		self.hold_percent = 0.0
		if xr_logic.switch_to_section(self.object, self.st.ini, xr_logic.pick_section_from_condlist(db.actor, self.object, self.st.on_hold.condlist)) then
			self.object:set_tip_text("")
			
			if self.st.tooltip then -- +UP
				self.object:set_tip_text(self.st.tooltip) -- +UP
			end -- +UP

			self:complete_hold()
		end
	end
end

function sr_button:try_switch()
	local st = db.storage[self.object:id()]
	if st.active_scheme and st.active_scheme == "sr_button" and self.st.on_press then

		if xr_logic.switch_to_section(self.object, self.st.ini,
		   xr_logic.pick_section_from_condlist(db.actor, self.object, self.st.on_press.condlist)) then
		   
		if self.st.hold then
			self:complete_hold()
		end
		
		self.object:set_tip_text("")

		if self.st.tooltip then -- +UP
			self.object:set_tip_text(self.st.tooltip) -- +UP
		end -- +UP

		if self.st.local_use then
			return true
		end
		   
		if OnServer() then
			local packet = net_packet()
			u_EventGen(packet, 124, self.object:id()) --GE_BUTTON_CHANGE_STATE
			u_EventSend(packet)
		end
		
		return true
		end
	end
	return false
end

function sr_button:update(delta)
	if self.st.hold and self.hold_percent > 0.0 then
        if time_global() - self.last_hit_tm > 50 then
			self:reset_hold()
        end
    end
		
	local actor = db.actor

	if xr_logic.try_switch_to_another_section(self.object, self.st, actor) then
		return
	end	
end

---------------------------------------------------------------------------------------------------------------------
function add_to_binder(npc, ini, scheme, section, storage)
	printf("DEBUG: add_to_binder: scheme='%s', section='%s'", scheme, section)

	local new_action = sr_button(npc, storage)

	-- Зарегистрировать все actions, в которых должен быть вызван метод reset_scheme при изменении настроек схемы:
	xr_logic.subscribe_action_for_events(npc, storage, new_action)
end

function set_scheme(npc, ini, scheme, section, gulag_name)
	local st = xr_logic.assign_storage_and_bind(npc, ini, scheme, section)
	st.logic = xr_logic.cfg_get_switch_conditions(ini, section, npc)
	
	st.tooltip  = utils.cfg_get_string(ini, section, "tooltip", npc, false, "")
	st.on_press  = xr_logic.cfg_get_condlist(ini, section, "on_press", npc)
	
	st.hold = utils.cfg_get_bool(ini, section, "hold", npc, false, false)
	
	if st.hold then
		st.on_hold = xr_logic.cfg_get_condlist(ini, section, "on_hold", npc)
		st.hold_multi = utils.cfg_get_number(ini, section, "hold_time_multi", nil, false, 2)
	end
	
	st.local_use = utils.cfg_get_bool(ini, section, "local_use", npc, false, false)
	npc:set_local_use(st.local_use)
	
	if st.tooltip then
		npc:set_tip_text(st.tooltip)
	else
		npc:set_tip_text("")
	end
end
