-- This file is used for indexing story flags

-- +SP
flags_to_id = {
	["DF_ARENA_FIGHT_1_READY"] = 1,
	["DF_ARENA_FIGHT_2_READY"] = 2,
	["DF_ARENA_FIGHT_3_READY"] = 3,
	["DF_ARENA_FIGHT_4_READY"] = 4,
	["DF_ARENA_FIGHT_5_READY"] = 5,
	["DF_ARENA_FIGHT_START"] = 6,
	["DF_ARENA_FIGHT_1_END"] = 7,
	["DF_ARENA_FIGHT_2_END"] = 8,
	["DF_ARENA_FIGHT_3_END"] = 9,
	["DF_ARENA_FIGHT_4_END"] = 10,
	["DF_ARENA_FIGHT_5_END"] = 11
}
id_to_flags = {
	[1] = "DF_ARENA_FIGHT_1_READY",
	[2] = "DF_ARENA_FIGHT_2_READY",
	[3] = "DF_ARENA_FIGHT_3_READY",
	[4] = "DF_ARENA_FIGHT_4_READY",
	[5] = "DF_ARENA_FIGHT_5_READY",
	[6] = "DF_ARENA_FIGHT_START",
	[7] = "DF_ARENA_FIGHT_1_END",
	[8] = "DF_ARENA_FIGHT_2_END",
	[9] = "DF_ARENA_FIGHT_3_END",
	[10] = "DF_ARENA_FIGHT_4_END",
	[11] = "DF_ARENA_FIGHT_5_END"
}
